### ISSUE TITLE
View crashes app (black screen)

### ISSUE THREAD

**Issue by FrederikBolding** [NAXAM/mapbox-xamarin-forms#10]
Hi,

I've been attempting to implement your library in a small Xamarin Forms application that I've been working on. However, as soon as I switch to the page with the MapView on it, the application (and emulator crashes) and I'm left with a black screen. I've only implemented the code in the readme file, but also tested with the sample code.

Any ideas?

Thanks in advance!

**Comment by kanvuduc** [comment]
Have you run the sample code ok? Which platform did you get the issue, Android or iOS?

We are currently using this in our app without that issue. You could try out by searching for Flexgrid on App Store.

Cheers.

**Comment by FrederikBolding** [comment]
The sample is running fine. I'm trying to run my own project on an Android emulator.

**Comment by FrederikBolding** [comment]
I've just run it successfully on my own project. I was missing the following tag `<service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService" />` in my manifest. Apparently, that causes a hard crash.
