### ISSUE TITLE
iOS project   Reference missing 

### ISSUE THREAD

**Issue by Fraguelrok** [NAXAM/mapbox-xamarin-forms#13]
Hi,

When i try to build/deploy on iOS, the project throws an exception : 

error : Can't resolve the reference 'CoreLocation.CLLocationCoordinate2D Mapbox.MGLCoordinateBounds::sw', referenced from the method 'System.Threading.Tasks.Task`1<Naxam.Controls.Mapbox.Forms.OfflinePack> Naxam.Controls.Mapbox.Platform.iOS.OfflineStorageService::DownloadMap(Naxam.Controls.Mapbox.Forms.OfflinePackRegion,System.Collections.Generic.Dictionary`2<System.String,System.String>,Naxam.Controls.Mapbox.Forms.IOfflineStorageDelegate)' in 'Naxam.Mapbox.iOS, Version=3.6.0.3, Culture=neutral, PublicKeyToken=null'._

My android project works fine.

Best Regards.

**Comment by fleuverouge** [comment]
Hi @Fraguelrok
 Sorry for the late reply. Please try our latest package to see if the problem remains.
Regards.

**Comment by tuyen-vuduc** [comment]
Plz reopen if you still get it, @Fraguelrok
