### ISSUE TITLE
Please update nuget with latest code

### ISSUE THREAD

**Issue by jeandomagni** [NAXAM/mapbox-xamarin-forms#17]
Hello,

Thank you for great job on this project. Could you please update nuget with lates code.

Thanks.

**Comment by nghiahaminh25101995** [comment]
@jeandomagni I upgraded to the latest version (5.5.0) 4 day ago.

**Comment by tuyen-vuduc** [comment]
@jeandomagni If you find it work at your end, plz pack and use the package locally. We will publish package when we think it's ready for new changes.
