### ISSUE TITLE
Draw shapes with  LineLayer  to represent fields

### ISSUE THREAD

**Issue by Goldstrike** [NAXAM/mapbox-xamarin-forms#22]
Hello,

A customer contacted me because he would like to use maps that allow him to display and locate "private areas" (like plots for a farmer) through layers drawn on the map.
The expected result looks like [this](https://preview.ibb.co/dAD8sy/Google_Maps.jpg).

I've seen that MapBox allows to draw shapes on their map, like in this [sample](https://bemky.github.io/mapbox-gl-draw-freehand-mode/).

So I would like to know if it's possible to "import" the areas through shapes that have been created through an admin web app with your plugin (by using LineLayer for example). Or is there another approach that would be better?

**Comment by tuyen-vuduc** [comment]
Hi,

Yes, it's possible.

Please check out latest version and samples.

Cheers.
