### ISSUE TITLE
Custom Map Tiles

### ISSUE THREAD

**Issue by ImCarrot** [NAXAM/mapbox-xamarin-forms#25]
Hi I was wondering if the SDK supports custom vector Map tiles . If yes then how can I use it? Any information would be of great help.

**Comment by fleuverouge** [comment]
Hi @ImCarrot ,

The current XForms version hasn't implemented that feature.

**Comment by tuyen-vuduc** [comment]
@ImCarrot Plz check the latest version to see if it fits your need. Naxam could absolutely provide this feature on a contract.
