### ISSUE TITLE
When downloading an offline map. Getting an `Unable to resolve host` error

### ISSUE THREAD

**Issue by KevM** [NAXAM/mapbox-xamarin-forms#32]
When in the emulator offline maps **is working for me** with the code below.

When on device (Lenovo Tab 4 7" running Android 7.1), while downloading an offline with map with `40000` total resources I get 327 resources downloaded and then get the following error. This happens each time I try to download the region. 

#### Error raised on the offline storage service
```
System.ApplicationException: Offline pack failed to download. Error message: Unable to resolve host "api.mapbox.com": No address associated with hostname occurred
```

#### Device Log

```
Time	Device Name	Type	PID	Tag	Message
09-06 13:37:22.935	LENOVO TB-8504F	Error	7521	mbgl	{GLThread 375}[Style]: Failed to load tile 16/52034/28851=>16 for source composite: Unable to resolve host "api.mapbox.com": No address associated with hostname
09-06 13:37:22.936	LENOVO TB-8504F	Info	7521	mono-stdout	[ERROR] Unable to resolve host "api.mapbox.com": No address associated with hostname REASON_CONNECTION
```

I thought it might be rate or resource limiting. But I added a credit card to my mapbox account and that didn't fix it.

### Code

Below is my calling code (I am wrapping the control in observables)
```cs
return Observable.Create<OfflinePack>(async o =>
{
    var disposables = new CompositeDisposable();
    var offlinePack = await _offlineStorageService.DownloadMap(offlineRegion, packInfo);

    _offlineStorageService.RequestPackProgress(offlinePack);

    // For some reason this event only fires when the service is asked for changes.
    var packProgressChanged = Observable.FromEventPattern<OSSEventArgs>(
            h => _offlineStorageService.OfflinePackProgressChanged += h,
            h => _offlineStorageService.OfflinePackProgressChanged -= h)
        .Select(e => e.EventArgs.OfflinePack)
        .Where(olp => olp.Id == offlinePack.Id);

    packProgressChanged.Subscribe(olp =>
    {
        if (olp.State == OfflinePackState.Completed)
        {
            o.OnCompleted();
            return;
        }
        o.OnNext(olp);
    }).AddTo(disposables);

    var packGotError = Observable.FromEventPattern<OSSErrorEventArgs>(
            h => _offlineStorageService.OfflinePackGotError += h,
            h => _offlineStorageService.OfflinePackGotError -= h)
        .Select(e => e.EventArgs.ErrorMessage);

    packGotError
        .Subscribe(errorMessage =>o.OnError(new ApplicationException($"Offline pack failed to download. Error message: {errorMessage}")))
        .AddTo(disposables);

    return disposables;
});
```

**Comment by tuyen-vuduc** [comment]
It would be an issue of Mapbox SDK. Have you checked with native SDK?

**Comment by KevM** [comment]
> Have you checked the native SDK.

Can you tell me more about what you mean here? Write an Android app that does the same against the native Mapbox SDK?

**Comment by KevM** [comment]
I have more information to add. I noticed that I was able to successfully download maps using the Mapbox basic style. When I went to style similar to what we want to use with a satellite layer (16-22) zoomlevel. I started to get the error again.

**Comment by KevM** [comment]
Another small note. When I run the app in the debugger I am much more likely to get the error (above) than when when I am not debugging.

**Comment by swapnil591** [comment]
@KevM  can you please check this repo demo app with offline mode
i found below result when load downloaded map
![screenshot_2018-11-05-17-24-50-378](https://user-images.githubusercontent.com/16575694/47997485-055e3d80-e122-11e8-8450-8424265aae67.jpeg)

**Comment by KevM** [comment]
That seems about what my experience is. I get no map after downloading a map and going offline.
