### ISSUE TITLE
unable to load downloaded map in offline mode . 

### ISSUE THREAD

**Issue by swapnil591** [NAXAM/mapbox-xamarin-forms#41]
checked demo project of this repo for offline mode also not working in it.

**Comment by KevM** [comment]
We've had the same problem.

**Comment by aquabay** [comment]
> checked demo project of this repo for offline mode also not working in it.

Make sure "CenterLocation" is initialized and is not null before calling DownloadMap.

**Comment by aquabay** [comment]
same

**Comment by swapnil591** [comment]
No success yet.
Offline map in Xamarin.forms is not possible yet.

**Comment by tuyen-vuduc** [comment]
Hi,

Please check out latest version and samples.

Cheers.
