### ISSUE TITLE
Visible Bounding Box (getVisibleRegion)?

### ISSUE THREAD

**Issue by MattPadXchange** [NAXAM/mapbox-xamarin-forms#42]
Is there a way in MapView or otherwise to get the bounding area(lat,long) of the user's current visible bounding box?  I'd imagine the ZoomLevel & Window-extents would be some of what is necessary.

I see in "DownloadMap" there is a reference to CoordinateBounds, but don't see it being set in such a way to get this info.

**Comment by tuyen-vuduc** [comment]
Hi,

Please check out latest version and samples.

Cheers.
