### ISSUE TITLE
use Mapbox in xamarin froms

### ISSUE THREAD

**Issue by iam58i** [NAXAM/mapbox-xamarin-forms#45]
Hi;
I develop with xamarin forms (visual studio 2017) for andorid and iOs apps.
I need Get lat and long when user tapped on mapview and
I need set marker on mapview after tapped.
please help me.
thanks

**Comment by tuyen-vuduc** [comment]
Hi,

It's now possible by adding a new Symbol Annotation when tapping on Map.

Plz check out all the samples or Symbol Annotation samples.

Cheers.
