### ISSUE TITLE
How to detect that map has been panned

### ISSUE THREAD

**Issue by klzig** [NAXAM/mapbox-xamarin-forms#47]
I can detect a tap on the map using DidTapOnMapCommand but there is no equivalent for panning or scrolling or swiping.  I've so far been unable to detect gestures using OnPanUpdated or OnSwipeUpdated.  The map.PropertyChanged event works sometimes but is unreliable, don't think it was intended for this.

What event will tell me that the map has been panned?  I'm testing on iOS and Android hardware.

**Comment by tuyen-vuduc** [comment]
Hi,

Thanks for checking out the library.

Not all events are exposed yet.

We are very welcome community contribution.

Cheers.
