### ISSUE TITLE
"Can't resolve reference get_Platform()" when targeting connected iPhone, Forms 4.0.0

### ISSUE THREAD

**Issue by klzig** [NAXAM/mapbox-xamarin-forms#48]
Upgraded a working project to the preview of Forms 4.0.0.  Now my iOS build breaks when targeting a connected iPhone 6S.  Android and iOS simulator targets build and deploy as before.  The error:

`Can't resolve the reference 'Xamarin.Forms.Internals.IPlatform Xamarin.Forms.Element::get_Platform()', referenced from the method 'System.Void Naxam.Mapbox.Platform.iOS.Extensions.FormsViewContainer::Dispose(System.Boolean)' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.	CTForms.iOS`

According to Microsoft this is a problem with the Naxam.Mapbox component.
https://github.com/xamarin/Xamarin.Forms/issues/4841

**Comment by tuyen-vuduc** [comment]
Hi,

Plz check out latest version and samples.

Cheers.
