### ISSUE TITLE
'local' is an undeclared prefix

### ISSUE THREAD

**Issue by dara1400** [NAXAM/mapbox-xamarin-forms#49]
<local:MapView 
    x:Name="map" 
    VerticalOptions="FillAndExpand" 
    MapStyle="{Binding CurrentMapStyle}" 
    ZoomLevel="{Binding ZoomLevel}"
/>

Hello 
when I used the code above in my Xaml I got this error:

'local' is an undeclared prefix

**Comment by AnthonyLatty** [comment]
`local` seems to be an xmlns call that is declared in the heading of your xaml file which references the path to the plugin.
