### ISSUE TITLE
Annotation and Feature

### ISSUE THREAD

**Issue by charlenni** [NAXAM/mapbox-xamarin-forms#5]
I saw, that PointFeature inherits from PointAnnotation.

I assume, that this isn't correct. Annotation and Feature seem to be different things in Mapbox. A Feature consits of Geometries and are drawn on any Layer. Annotations are special Features, that are drawn on a special Layer and are clickable/have an InfoWindow. Is this correct or I'm wrong?

**Comment by fleuverouge** [comment]
Hi @charlenni, 
In my assumption, features are special annotations, as you can see in Mapbox iOS SDK documentation: [MGLFeature protocol](https://www.mapbox.com/ios-sdk/api/3.6.0/Protocols/MGLFeature.html). They also defined that [point feature is a subclass of a point annotation](https://www.mapbox.com/ios-sdk/api/3.6.0/Style%20Primitives.html#/c:objc(cs)MGLPointFeature).
 In our renderers & xforms implementations, we try to match the classes and interfaces as close as possible to the original ones in SDKs.

**Comment by charlenni** [comment]
As you can see in Mapbox Android SDK documentation, [Feature](https://www.mapbox.com/android-docs/api/mapbox-java/libjava-geojson/2.0.0/com/mapbox/services/commons/geojson/Feature.html) didn't derive from Annotation.

If you look at OSM data, you see, that a Feature consists of an id (from OSM database), one or more geometries and some tags. A vector map consists of many Features. They are drawn regarding the tags and the style. With this, you get the map. You don't need any Annotation to do this. You could see this in Android source: Feature is defined in the GeoJSON part.

A Annotation is a special Feature on the map. It has a geometry, a title/subtitle and you can click on it. It could have an id, but only for information, if you set one. In Android doc you could see, that Annotation derives direct from object. Btw. Feature too. And this is correct. They are two different things.

In short: Feature is a thing, that could be placed on a Layer, so that it is visible on the map. An Annotation is a thing, that is placed on a special Layer (annotation layer), that is clickable and could display an InfoWindow. All other map libraries except Mapbox iOS distinct this correct.

Xamarin.Forms could be used from iOS and Android. In the last days I look into Mapbox iOS and Mapbox Android. They look like two totally different products. Not even the names are different, but the behavior too. So it would be good to have a wrapper, so that the user could use both the same way. If you don't do this, it would be better not to use Xamarin.Forms and make two projects, one for iOS and one for Android. A good example for a Xamarin.Forms map project is [Xamarin.Forms.GoogleMaps](https://github.com/amay077/Xamarin.Forms.GoogleMaps). The library for iOS and Android could be used both in the same way. You don't have to think about differences in the implementations.

So, all this said, you have to say at the end, which classes and interfaces you want to follow: iOS, Android or create a wrapper around both, which is usable from both sides.

**Comment by kanvuduc** [comment]
@charlenni,

Thank you for your very long explanation.

We did create XF library based on and follow Mapbox iOS API. That's why you see the API for XF looks more iOS than Android. That's why you see Feature is derived from Annotation.

We agree that Mapbox for Android and Mapbox for iOS are really different from each other, so we really need to balance.

Cheers.

**Comment by charlenni** [comment]
Thank you for your fast answer.

Meanwhile I found this [issue #9540](https://github.com/mapbox/mapbox-gl-native/pull/9540) in Mapbox iOS. It seems, that the Mapbox guys encountered the problem by themselfs and try to change it. If I understand correct, they want to implement, that MGLFeature doesn't longer inherit from MGLAnnotation.

**Comment by kanvuduc** [comment]
That's a great finding. I think we should remove the current inheritance if it's ok.

**Comment by kmlshmaurya32** [comment]
how to get mapbox map zooming positon in ios
