### ISSUE TITLE
Clustering PointAnnotation markers with GeoJsonSource

### ISSUE THREAD

**Issue by aquabay** [NAXAM/mapbox-xamarin-forms#52]
I'm very new to MapBox but was hoping someone could help with this. Please advise if there is a better forum for this question.

I am trying to apply clustering of Markers (PointAnnotations) for a map. I have extended the Naxam.Controls.Mapbox.Platform.Droid.MapViewRenderer from the demo code with the folowing method:

        private const String MARKER_SOURCE = "markers-source";
        private const String MARKER_STYLE_LAYER = "markers-style-layer";

        private void AddMarkers(IList<PointAnnotation> markers)
        {
            var geoJsonOptions = new GeoJsonOptions();
            geoJsonOptions.WithCluster(true);
            geoJsonOptions.WithClusterMaxZoom(14);
            geoJsonOptions.WithClusterRadius(90);

            var markerIcon = context.Resources.GetBitmap("pin");
            map.AddImage("pin", markerIcon);

            IList<Feature> markerFeatures = new List<Feature>();
            for (int i = 0; i < markers.Count; i++)
            {
                foreach (var feature in markers[i].ToFeatureCollection().Features())
                {
                    markerFeatures.Add(feature);
                }
            }
            FeatureCollection featureCollection = FeatureCollection.FromFeatures(markerFeatures.ToArray());

            GeoJsonSource source = new GeoJsonSource(MARKER_SOURCE, featureCollection, geoJsonOptions);
            map.AddSource(source);

            /* Style layer: A style layer ties together the source and image and specifies how they are displayed on the map. */
            SymbolLayer markerStyleLayer = new SymbolLayer(MARKER_STYLE_LAYER, MARKER_SOURCE);
            markerStyleLayer.IconImageName = "pin";
            var icon = Context.GetIconFromResource(markerStyleLayer.IconImageName);
            markerStyleLayer.IsVisible = true;
            map.AddLayer(markerStyleLayer.ToNative() );
        }

Debugging shows that the source and layer are added to the MapboxMap but the markers are not rendered.

**Comment by tuyen-vuduc** [comment]
Hi,

This cluster sample is now available.

Please check it out.

Cheers.
