### ISSUE TITLE
InfoWindowTemplate implementation throws error using Xamarin Forms 3.5

### ISSUE THREAD

**Issue by rj-thomas** [NAXAM/mapbox-xamarin-forms#54]
Hi, 

It appears there is a breaking change sometime after Xamarin.Forms 3.1 that causes the InfoWindowTemplate implementation to throw an exception due to mismatched XF versions when you click on an annotation marker on the map.

An update of the Naxam.Mapbox.Forms  to the latest XF version resolves the issue, apart from an exception reading the platform in one method in the iOS project which is an unused variable anyway.

Cheers
rj

**Comment by tuyen-vuduc** [comment]
Hi,

InforWindow is being depreciated from Mapbox Android. We completely removed it for Android implementation even the property is still there.

Alternative solution not implemented yet.

Cheers.
