### ISSUE TITLE
No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() 

### ISSUE THREAD

**Issue by sooryanmohan** [NAXAM/mapbox-xamarin-forms#56]
Hi Naxam,

I am using Naxam.Mapbox.Droid(6.4.0.1) nugget package for integrating mapbox map in Xamarin forms.While initializing the mapbox sdk I am getting an exception.

{Java.Lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__) at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <42dc777b518744fdae9988e94489a4a0>:0 at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <42dc777b518744fdae9988e94489a4a0>:0 at Com.Mapbox.Mapboxsdk.Mapbox.GetInstance (Android.Content.Context p0, System.String p1) [0x0004b] in <1c4b424268aa42e29816c89b4cca3283>:0 at Alden.TaskAgent.UI.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00020] in E:\ConcertCare\OfflineMapTaskAgent\Alden.TaskAgent\Alden.TaskAgent.UI\TaskAgent.Droid\MainActivity.cs:34 --- End of managed Java.Lang.UnsatisfiedLinkError stack trace --- java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__) at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method) at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27) at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:39) at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:51) at md5de7a84ff76d1b924586c70e2529f1c90.MainActivity.n_onCreate(Native Method) at md5de7a84ff76d1b924586c70e2529f1c90.MainActivity.onCreate(MainActivity.java:31) at android.app.Activity.performCreate(Activity.java:6904) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) at android.app.ActivityThread.access$1100(ActivityThread.java:229) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:7331) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) }

Can you help me fixing the issue.

Thanks and Regards,

Sooryan

**Comment by tuyen-vuduc** [comment]
Hi,

Latest version is compiled with Mapbox 8.4 for Android.

Please check it out.
