### ISSUE TITLE
how to add a marker point on a specific location ?

### ISSUE THREAD

**Issue by jym92** [NAXAM/mapbox-xamarin-forms#59]
Hi, I use your package and It's work fine but now I want to add some markers on specific locations.

I just want to be able to add a marker with a specific size and color on a specific location( it's not important if the marker is a squarre or a circle).

but I don't find any advice or example to do it....

thanks for your help :)

**Comment by ChristianTBaker** [comment]
I don't work on this repo, but I've been working with it for a little bit.  Most of what you want can be achieved in the MainPageViewModel constructor.  If you just add a new PointAnnotation to the Annotations, it will add a new point marker.  You should be able to add any Annotation object here and it will be added to the map.  You can also directly set a new CenterLocation to start from here.  Hope that helps.  I'm trying to figure out if the Android and iOS librarys work from this repo.  They use the local namespace for the main project, but use nuget packages for android and iOS respectively.

**Comment by tuyen-vuduc** [comment]
Hi,

To add a marker point, it's adding a SymbolAnnotation to the map.

Please check out one of our samples ported from Android samples.

P/S: It's recommended to read Mapbox document first and/or to scan more info there.

Cheers.

**Comment by nhatng** [comment]
Hi @tuyen-vuduc 
Please help me to show marker with text. Although I've set value to properties: Tile, SubTitle of SymbolAnnotation object, but it only show image of marker only.

Please help me. It is urgent to me.
thank you very much
Nhat
