### ISSUE TITLE
Nuget install issue

### ISSUE THREAD

**Issue by PonsRepo** [NAXAM/mapbox-xamarin-forms#61]
java/lang/String;)Lcom/mapbox/geojson/Geometry;: defining a static interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: com.mapbox.geojson.Geometry.fromJson : (Ljava/lang/String;)Lcom/mapbox/geojson/Geometry;	App1.Android

**Comment by tuyen-vuduc** [comment]
Please increase your MinSDK version.

Cheers.

**Comment by PonsRepo** [comment]
My android version is 24 definitely. But it is giving the error. 
Please let me know. 
Thanks

**Comment by tuyen-vuduc** [comment]
```defining a static interface method requires --min-sdk-version >= 24```

It isn't the Android version on your device. It's the min SDK version of your Android project defined in manifest.xml.

Cheers.

**Comment by PonsRepo** [comment]
![image](https://user-images.githubusercontent.com/25751066/66970318-ebbbba80-f041-11e9-92ee-1820bdf27d46.png)

Yes. the min--sdk--version is 24 as you can see. It is Xamarin.Forms project. 
It is strange. 

Please let me know what I have done wrong.

**Comment by tuyen-vuduc** [comment]
It's really weird! Could you run my sample code?

**Comment by PonsRepo** [comment]
I have created a new Xamarin forms project and tried to install your NuGet. 
when I build it, it gives just save error. Please try it by yourself. 
Thanks.

**Comment by pepobit** [comment]
I have the same issue with min-sdk 24

**Comment by tuyen-vuduc** [comment]
Hi,

I just tried creating a totally new Xamarin.Forms app and adding the package. Its installation is ok.

On building for Android, it failed to find GeoJSON.NET for some reasons. Adding GeoJSON.NET directly to Android project, then it's up and running.

The default min-sdk is 21, so it should work well for 24.

Cheers.
