### ISSUE TITLE
Lỗi quá nhiều

### ISSUE THREAD

**Issue by hoangwy** [NAXAM/mapbox-xamarin-forms#73]
Hi team,
Truớc tiên cảm ơn team đã support lib này cho XF.
Nhưng....lỗi quá nhiều và mình thắc mắc không biết mục đích team bỏ thời gian làm ra cái để làm gì cuối cùng không sử dụng đuợc.
Nếu team không support nữa thì mình hy vọng team sẽ gỡ lib này để mọi nguời khỏi phải dùng
Chân thành và cảm ơn

**Comment by tuyen-vuduc** [comment]
Hi @hoangwy ,

Cám ơn bạn đã phản hồi.

Một thư viện khi sinh ra sẽ đáp ứng 1 nhu cầu nào đó của công việc. Với thư viện này, nó đáp ứng được cơ bản các yêu cầu nghiệp vụ của Naxam, đó là điều trước nhất.

Mapbox là một thư viện khổng lồ nên cần các bài toán cụ thể để khai thác các tính năng rồi bổ sung vào trong quá trình làm ứng dụng, do đó Naxam đưa thư viện này thành thư viện mở để cộng đồng có thể đóng góp thêm các tính năng mới cho thư viện để  ngày càng đầy đủ hơn.

Hiện tại rất nhiều ví dụ mẫu của Mapbox Android Native đã được chuyển đổi qua, phần lớn chạy tốt cho cả Android và iOS.

Việc bạn nói lỗi quá nhiều không giúp được gì cho việc cải tiến thư viện cả, hay ghi rõ lỗi của bạn là gì, cách thức tái hiện lỗi và kì vọng là gì.

Đây là thư viện mở MIT, vậy nên hay mạnh dạn thay đổi nó và tạo PR, Naxam sẽ sẵn sàng review và ghép những thay đổi của bạn vào.

Cám ơn.

**Comment by hoangwy** [comment]
Hi team,
"Việc bạn nói lỗi quá nhiều không giúp được gì cho việc cải tiến thư viện cả, hay ghi rõ lỗi của bạn là gì, cách thức tái hiện lỗi và kì vọng là gì."

Mình rất trân trọng công sức của team. Mình xinh cảm ơn!

Vậy bên team có thấy 12 issues đang open không?

Mình đã sử dụng lib này nhưng mình đã remove ngay vì không dùng đuợc.
không dùng đuợc không phải vì nó ko chạy mà vì một số chức năng căn bản của lib đã không dùng đuợc chứ mình chưa dùng những chức năng nâng.
Ví dụ:
- Android không show đuợc custom view khi tap vào Pin
- Khi tap vào Pin của thiết bị thì crash.
- ShowUserLocation thì không hoạt động
- CenterLocation thì lúc đuợc lúc không
...
Thân

**Comment by fleuverouge** [comment]
Hi @hoangwy ,

Cảm ơn bạn đã quan tâm tới thư viện bên mình. 

> Vậy bên team có thấy 12 issues đang open không

Đây là thư viện mã nguồn mở và khuyến khích sự đóng góp của cộng đồng (nếu không bọn mình đã tự share cho nhau và dùng nội bộ rồi). Trong thời gian dài thư viện hoạt động bình thường thì không thấy các bạn đâu, khi lỗi thì chỉ trích như thể bọn mình phá các bạn? Bọn mình không có nghĩa vụ fix mọi issue mọi lúc bạn nhé. Bọn mình không bắt ai phải sử dụng cả mà bạn "hy vọng team sẽ gỡ lib này để mọi nguời khỏi phải dùng".

**Comment by dothanhbinh41** [comment]
> Đây là thư viện mã nguồn mở và khuyến khích sự đóng góp của cộng đồng (nếu không bọn mình đã tự share cho nhau và dùng nội bộ rồi). Trong thời gian dài thư viện hoạt động bình thường thì không thấy các bạn đâu, khi lỗi thì chỉ trích như thể bọn mình phá các bạn? Bọn mình không có nghĩa vụ fix mọi issue mọi lúc bạn nhé. Bọn mình không bắt ai phải sử dụng cả mà bạn "hy vọng team sẽ gỡ lib này để mọi nguời khỏi phải dùng".

Thực sự hay

**Comment by hoangwy** [comment]
Hi team,
Mình chưa bao giờ phũ nhận cái đó. nhưng để mọi người có thể tham gia vào project thì trước tiên những chức năng căn bản phải chạy ok thì mọi người mới có hứng thú.
khi bạn sử dụng một lib nào đó mà bị lỗi những thứ căn bản thì bạn có muốn sử dụng tiếp không chứ chưa nói tới chuyện folk về rồi fix.
Mình chỉ muốn góp ý. sao mấy bạn lại xù lông lên vậy nhỉ.
vậy bao giờ lib của mấy bạn mới ngon lên được.
thân

**Comment by tuyen-vuduc** [comment]
@hoangwy,

Cám ơn bạn, như tôi có đề cập ở trên, việc phát triển thư viện này là để đáp ứng nhu cầu nội tại của Naxam và chạy phù hợp trong dự án của Naxam là đủ.

Naxam để mã nguồn mở vì
- Đầu tiên là chia sẻ kiến thức, nếu thấy dùng được, cộng đồng có thể sử dụng cả/cóp nhặt phần code dùng được/thậm chí sửa đổi cho phù hợp với nhu cầu, tốt hơn nữa là có thêm sự đóng góp từ cộng đồng
- 1 thư viện nguồn mở khi phát triển, nó có mục đích của nó, và nó sẽ không bao phủ toàn bộ các ngữ cảnh khác nhau do giới hạn về nguồn lực (tiền, người, thời gian)
- Thư viện Mapbox là một thư viện rất rộng, Naxam chỉ sử dụng 1 tập nhỏ trong số các tính năng mà Mapbox cung cấp, nên trong Naxam thì thư viện này là ok, nhưng với cộng đồng, có thể có sự thiếu sót

Nếu @hoangwy có thể đóng góp để sửa các lỗi của thư viện thì vô cùng hoan nghênh, còn không vui lòng không chỉ trích/đả kích hay đòi hỏi Naxam phải gỡ thư viện này.

Xin dừng trao đổi về chủ đề này ở đây.

Trân trọng.
