### ISSUE TITLE
AddStyleImage takes string casted to ImageSource

### ISSUE THREAD

**Issue by RogerSchmidlin** [NAXAM/mapbox-xamarin-forms#78]
Got this out of the sample code. The IconImageSource takes an ImageSource. But giving it an image source like in the commented out line it fails. Using a string and casting it to ImageSource works. I don't understand. Passing in just a string doesn't work either, eventhough IconImageSource has a constructor for it.
`            
//IconImageSource icon = ImageSource.FromResource("PowerPlan.Images.Map.blue_marker_view.png");
IconImageSource icon = (ImageSource)"gilbert.png";
map.Functions.AddStyleImage(icon);
`

**Comment by tuyen-vuduc** [comment]
😁, great finding. Mapbox only support Android/iOS native resources. Your way wont work.
